class AttributeTagCreator:
    @staticmethod
    def create():
        attribute_tags = list()
        attribute_tags.append([['form'], 'accept'])
        attribute_tags.append([['caption', 'col', 'div', 'embed', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'iframe'
                                , 'img', 'input', 'legend', 'object', 'p', 'table', 'tbody', 'thead', 'tfoot', 'td'
                                , 'th', 'tr'], 'align'])
        attribute_tags.append([['body'], 'alink'])
        attribute_tags.append([['iframe'], 'allowtransparency'])
        attribute_tags.append([['object'], 'archive'])
        attribute_tags.append([['td', 'th'], 'axis'])
        attribute_tags.append([['body', 'table', 'thead', 'tbody', 'tfoot', 'tr', 'td', 'th'], 'background'])
        attribute_tags.append([['body', 'table', 'td', 'th', 'tr'], 'bgcolor'])
        attribute_tags.append([['object'], 'border'])
        attribute_tags.append([['table'], 'bordercolor'])
        attribute_tags.append([['table'], 'cellpadding'])
        attribute_tags.append([['table'], 'cellspacing'])
        attribute_tags.append([['col', 'tbody', 'thead', 'tfoot', 'td', 'th', 'tr'], 'char'])
        attribute_tags.append([['col', 'tbody', 'thead', 'tfoot', 'td', 'th', 'tr'], 'charoff'])
        attribute_tags.append([['a', 'link'], 'charset'])
        attribute_tags.append([['object'], 'classid'])
        attribute_tags.append([['br'], 'clear'])
        attribute_tags.append([['object'], 'code'])
        attribute_tags.append([['object'], 'codebase'])
        attribute_tags.append([['object'], 'codetype'])
        attribute_tags.append([['hr'], 'color'])
        attribute_tags.append([['dl', 'ol', 'ul'], 'compact'])
        attribute_tags.append([['a'], 'coords'])
        attribute_tags.append([['a', 'applet', 'button', 'div', 'fieldset', 'frame', 'iframe', 'img', 'input', 'label'
                                   , 'legend', 'marquee', 'object', 'param', 'select', 'span', 'textarea'], 'datafld'])
        attribute_tags.append([['button', 'div', 'input', 'label', 'legend', 'marquee', 'object', 'option', 'select'
                                , 'span', 'table'], 'dataformatas'])
        attribute_tags.append([['table'], 'datapagesize'])
        attribute_tags.append([['a', 'applet', 'button', 'div', 'frame', 'iframe', 'img', 'input', 'label'
                                   , 'legend', 'marquee', 'object', 'option', 'select', 'span', 'textarea'], 'datasrc'])
        attribute_tags.append([['object'], 'declare'])
        attribute_tags.append([['script'], 'event'])
        attribute_tags.append([['script'], 'for'])
        attribute_tags.append([['table'], 'frame'])
        attribute_tags.append([['iframe'], 'frameborder'])
        attribute_tags.append([['td', 'th'], 'height'])
        attribute_tags.append([['embed', 'iframe', 'img', 'input', 'object'], 'hspace'])
        attribute_tags.append([['input'], 'ismap'])
        attribute_tags.append([['body'], 'link'])
        attribute_tags.append([['img'], 'lowsrc'])
        attribute_tags.append([['body'], 'marginbottom'])
        attribute_tags.append([['body', 'iframe'], 'marginheight'])
        attribute_tags.append([['body'], 'marginleft'])
        attribute_tags.append([['body'], 'marginright'])
        attribute_tags.append([['body'], 'margintop'])
        attribute_tags.append([['body', 'iframe'], 'marginwidth'])
        attribute_tags.append([['a', 'link'], 'methods'])
        attribute_tags.append([['embed', 'img', 'option'], 'name'])
        attribute_tags.append([['area'], 'nohref'])
        attribute_tags.append([['hr'], 'noshade'])
        attribute_tags.append([['td', 'th'], 'nowrap'])
        attribute_tags.append([['head'], 'profile'])
        attribute_tags.append([['table'], 'rules'])
        attribute_tags.append([['meta'], 'scheme'])
        attribute_tags.append([['td'], 'scope'])
        attribute_tags.append([['iframe'], 'scrolling'])
        attribute_tags.append([['a'], 'shape'])
        attribute_tags.append([['hr'], 'size'])
        attribute_tags.append([['object'], 'standby'])
        attribute_tags.append([['table'], 'summary'])
        attribute_tags.append([['link'], 'target'])
        attribute_tags.append([['body'], 'text'])
        attribute_tags.append([['li', 'param', 'ul'], 'type'])
        attribute_tags.append([['a', 'link'], 'urn'])
        attribute_tags.append([['input'], 'usemap'])
        attribute_tags.append([['col', 'tbody', 'thead', 'tfoot', 'td', 'th', 'tr'], 'valign'])
        attribute_tags.append([['param'], 'valuetype'])
        attribute_tags.append([['html'], 'version'])
        attribute_tags.append([['body'], 'vlink'])
        attribute_tags.append([['embed', 'iframe', 'img', 'input', 'object'], 'vspace'])
        attribute_tags.append([['col', 'hr', 'pre', 'table', 'td', 'th'], 'width'])

        return attribute_tags
